events {
    worker_connections 4096;
}

http {
    upstream bank_cluster {
        hash $http_x_sender_vpa consistent;
        server spring-bank-1:8080;
        server spring-bank-2:8080;
        server spring-bank-3:8080;
    }

    server {
        listen 8080;
        client_max_body_size 100k;

        location / {
            proxy_pass http://bank_cluster;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_connect_timeout 5s;
            proxy_read_timeout 60s;
        }
    }
}
