package com.offline.payment.repository;

import com.offline.payment.model.Account;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

@Repository
public interface AccountRepository extends JpaRepository<Account, String> {
    // Basic CRUD is auto-generated by extending JpaRepository
}